spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:impact}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:asdf}
  access-exp: ${TOKEN_ACCESS_EXP:3600}

ngrok:
  enabled: true
  auth-token: ${NGROK_AUTH_TOKEN}
  command: http --domain=precise-socially-mackerel.ngrok-free.app 8080